# NOT Used This time
NUM_FOLDS = 4
IMAGE_SIZE = 256
BATCH_SIZE = 32
EFFICIENTNET_SIZE = 0
WEIGHTS = "imagenet"

MIXUP_PROB = 0.0
EPOCHS = 20
R_ANGLE = 0 / 180 * np.pi
S_SHIFT = 0.0
T_SHIFT = 0.0
LABEL_POSITIVE_SHIFT = 0.99